### ISSUE TITLE
Add support for RPCS3's patch.yml

### ISSUE THREAD

**Issue by RagdollClash** [HyperPolygon64/Unleashed-Mod-Manager#2]
Instead of decrypting the PS3's executable and patching it manually, you can instead make use of RPCS3's patch function. There's information on how to set the file up on the [RPCS3 wiki](https://wiki.rpcs3.net/index.php?title=Help:Game_Patches). This will save time for the end user as it won't have to recompile the executable every time and will instead recompile the edited portion of the executable.

It's also worth mentioning that RPCS3 allows you to decrypt the executable, it's under `Utilities -> Decrypt PS3 Binaries`

**Comment by hyperbx** [comment]
Unleashed Mod Manager is also designed to work on real hardware, so adding support for RPCS3 patches wasn't really a priority.

**Comment by RagdollClash** [comment]
Ahh, I forgot about real hardware. There is a way to inject RPCS3 patches into the EBOOT, the [Persona modding community](https://shrinefox.com/guides/2019/06/12/persona-5-ps3-eboot-patching/) has a tool for that called [RPCS3PatchEboot](https://github.com/TGEnigma/RPCS3PatchEboot). It could be worth looking into someday.

**Comment by hyperbx** [comment]
The Mod Manager's patch scripting language ([documented here](https://github.com/Knuxfan24/Sonic-06-Mod-Manager/wiki/Scripting-Language)) supports XEX/BIN encryption and decryption with ``EncryptExecutable()`` and ``DecryptExecutable()`` - they just call external applications to deal with it, since there's not really any library I can use with C# to do such things (and I'm in no way experienced to write something like that, haha).

By switching to RPCS3's stuff, you'd probably be taking off milliseconds for the time taken to patch the executable and get things running (minus the file redirection). On the plus side, it works for both emulators and real hardware. 😛

**Comment by hyperbx** [comment]
Worth noting that if you want to write some patches to be included with Unleashed Mod Manager by default, [make a PR on this repo](https://github.com/HyperPolygon64/Unleashed-Mod-Manager-Patches).

The way I'm handling patch downloading for both this and Sonic '06 Mod Manager is [a bit bodged](https://github.com/HyperPolygon64/Unleashed-Mod-Manager/blob/master/Unleashed-Mod-Manager/src/Environment3/RushInterface.cs#L1386) (since you need to manually add the link to the patch in the repo), but it _somehow_ works fine.
